spring:
  datasource:
    url: jdbc:oracle:thin:@172.30.34.100:1521/orcl
    username: bigscreen
    password: 123456
    driverClassName: oracle.jdbc.driver.OracleDriver
lucene_index:
  location: temp\\index